//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class jogadas
    {
        public int id { get; set; }
        public int id_jogo { get; set; }
        public int campo { get; set; }
        public Nullable<int> subcampo { get; set; }
        public string jogada { get; set; }
    
        public virtual Jogo Jogo { get; set; }
    }
}
